title: ZedMAJOR aka Kuro Zim
description: 隐藏身份并无用处，直面现实才有出路。
theme: just-the-docs

url: 

logo: "/assets/images/NewLogoFullSize.png"

color_scheme: zim

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: 'k'
  
mermaid:
  version: "9.1.3"

nav_enabled: true
nav_sort: default

heading_anchors: true

enable_copy_code_button: true

back_to_top: true
back_to_top_text: "返回页顶"

collections:
  work:
    output: true
    permalink: /:collection/:path/
  cowork:
    output: true
    permalink: /:collection/:path/
  subwork:
    output: true
    permalink: /:collection/:path/
  misc:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/
    
just_the_docs:
  collections:
    work:
      name: 个人歌曲
      nav_fold: true
    cowork:
      name: 合作歌曲
      nav_fold: true
    subwork:
      name: 鬼畜二创
      nav_fold: true
    misc:
      name: 其他
      nav_fold: true
    others:
      name: 关于
      nav_fold: true

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: 提示
    color: blue
  new:
    title: 更新！
    color: green
  note:
    title: 说明
    color: purple
  warning:
    title: 警告
    color: red

aux_links:
  "Bilibili":
    - "https://space.bilibili.com/3690977717914229"
  "Dizzylab":
    - "https://www.dizzylab.net/l/Zedmajor%20aka%20Kuro%20Zim"